2021/02/14 11:27:45 [error] 29#29: *1 open() "/app/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: panda.lc, request: "GET /favicon.ico HTTP/1.1", host: "localhost:3001", referrer: "http://localhost:3001/"
2021/02/14 11:27:52 [error] 29#29: *1 open() "/app/api/healthcheck" failed (2: No such file or directory), client: 172.18.0.1, server: panda.lc, request: "GET /api/healthcheck HTTP/1.1", host: "localhost:3001"
2021/02/14 11:29:26 [error] 29#29: *3 open() "/app/api/healthcheck" failed (2: No such file or directory), client: 172.18.0.1, server: panda.lc, request: "GET /api/healthcheck HTTP/1.1", host: "localhost:3001"
2021/02/14 11:30:48 [error] 29#29: *5 "/app/api/healthcheck/index.html" is not found (2: No such file or directory), client: 172.18.0.1, server: panda.lc, request: "GET /api/healthcheck/ HTTP/1.1", host: "localhost:3001"
2021/02/14 11:34:23 [error] 29#29: *7 open() "/app/api/healthcheck" failed (2: No such file or directory), client: 172.18.0.1, server: panda.lc, request: "GET /api/healthcheck HTTP/1.1", host: "localhost:3001"
2021/02/14 11:37:21 [emerg] 1#1: "http" directive is not allowed here in /etc/nginx/conf.d/default.conf:1
2021/02/14 11:37:29 [emerg] 1#1: "http" directive is not allowed here in /etc/nginx/conf.d/default.conf:1
2021/02/14 11:37:45 [emerg] 1#1: "http" directive is not allowed here in /etc/nginx/conf.d/default.conf:1
2021/02/14 11:40:53 [emerg] 1#1: "proxy_redirect" directive is duplicate in /etc/nginx/conf.d/default.conf:20
2021/02/14 11:41:33 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "localhost:3001"
2021/02/14 11:42:12 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "localhost:3001"
2021/02/14 11:43:15 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:3001"
2021/02/14 11:45:07 [emerg] 1#1: host not found in upstream "IPorURL_адрес_сервера" in /etc/nginx/conf.d/default.conf:28
2021/02/14 11:46:20 [emerg] 1#1: unknown directive "//" in /etc/nginx/conf.d/default.conf:27
2021/02/14 11:46:43 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:3001"
2021/02/14 11:51:56 [emerg] 1#1: unexpected "}" in /etc/nginx/conf.d/default.conf:13
2021/02/14 11:52:01 [emerg] 1#1: unexpected "}" in /etc/nginx/conf.d/default.conf:13
2021/02/14 11:53:12 [emerg] 1#1: unexpected "}" in /etc/nginx/conf.d/default.conf:12
2021/02/14 11:53:31 [emerg] 1#1: unexpected "}" in /etc/nginx/conf.d/default.conf:12
2021/02/14 11:54:11 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:3001"
2021/02/14 11:54:11 [warn] 28#28: *1 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:3001"
2021/02/14 11:54:11 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:3001"
2021/02/14 11:54:11 [warn] 28#28: *1 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:3001"
2021/02/14 11:54:28 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:3001"
2021/02/14 11:54:28 [warn] 28#28: *1 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:3001"
2021/02/14 11:54:28 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:3001"
2021/02/14 11:54:28 [warn] 28#28: *1 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:3001"
2021/02/14 11:54:31 [error] 28#28: *1 no live upstreams while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET /api/healthcheck HTTP/1.1", upstream: "http://localhost/api/healthcheck", host: "localhost:3001"
2021/02/14 12:09:14 [emerg] 1#1: host not found in upstream "private_ip_address" in /etc/nginx/conf.d/default.conf:5
2021/02/14 12:12:50 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET /openserver/phpmyadmin/ HTTP/1.1", upstream: "http://127.0.0.1:3001/openserver/phpmyadmin/", host: "localhost"
2021/02/14 12:12:50 [warn] 29#29: *2 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET /openserver/phpmyadmin/ HTTP/1.1", upstream: "http://127.0.0.1:3001/openserver/phpmyadmin/", host: "localhost"
2021/02/14 12:12:50 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET /openserver/phpmyadmin/ HTTP/1.1", upstream: "http://127.0.0.1:3001/openserver/phpmyadmin/", host: "localhost"
2021/02/14 12:12:50 [warn] 29#29: *2 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET /openserver/phpmyadmin/ HTTP/1.1", upstream: "http://127.0.0.1:3001/openserver/phpmyadmin/", host: "localhost"
2021/02/14 12:12:50 [error] 29#29: *2 no live upstreams while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost", referrer: "http://localhost/openserver/phpmyadmin/"
2021/02/14 12:13:00 [error] 29#29: *2 no live upstreams while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET /openserver/phpmyadmin/ HTTP/1.1", upstream: "http://localhost/openserver/phpmyadmin/", host: "localhost"
2021/02/14 12:13:00 [error] 29#29: *2 no live upstreams while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost", referrer: "http://localhost/openserver/phpmyadmin/"
2021/02/14 12:13:10 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:13:10 [warn] 29#29: *2 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:13:10 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:13:10 [warn] 29#29: *2 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:13:10 [error] 29#29: *2 no live upstreams while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost", referrer: "http://localhost/"
2021/02/14 12:13:19 [error] 29#29: *2 no live upstreams while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "localhost"
2021/02/14 12:13:20 [error] 29#29: *2 no live upstreams while connecting to upstream, client: 172.18.0.1, server: pandich.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost", referrer: "http://localhost/"
2021/02/14 12:14:37 [emerg] 1#1: "http" directive is not allowed here in /etc/nginx/conf.d/default.conf:1
2021/02/14 12:16:28 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:16:28 [warn] 29#29: *1 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:16:28 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:16:28 [warn] 29#29: *1 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:16:28 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost", referrer: "http://localhost/"
2021/02/14 12:18:05 [emerg] 1#1: host not found in upstream "panda.loc" in /etc/nginx/conf.d/default.conf:21
2021/02/14 12:19:45 [emerg] 1#1: invalid host in "[::]8080" of the "listen" directive in /etc/nginx/conf.d/default.conf:4
2021/02/14 12:23:56 [emerg] 1#1: unknown directive "​" in /etc/nginx/conf.d/default.conf:14
2021/02/14 12:24:00 [emerg] 1#1: unknown directive "​" in /etc/nginx/conf.d/default.conf:14
2021/02/14 12:24:32 [emerg] 1#1: unknown directive "​" in /etc/nginx/conf.d/default.conf:14
2021/02/14 12:24:58 [emerg] 1#1: unknown directive "​" in /etc/nginx/conf.d/default.conf:14
2021/02/14 12:26:08 [emerg] 1#1: unknown directive "​" in /etc/nginx/conf.d/default.conf:14
2021/02/14 12:27:40 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:27:40 [warn] 28#28: *1 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:27:40 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:27:40 [warn] 28#28: *1 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:27:41 [error] 28#28: *1 no live upstreams while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost", referrer: "http://localhost/"
2021/02/14 12:29:43 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:29:43 [warn] 29#29: *2 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:29:43 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:29:43 [warn] 29#29: *2 upstream server temporarily disabled while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost"
2021/02/14 12:29:43 [error] 29#29: *2 no live upstreams while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost", referrer: "http://localhost/"
2021/02/14 12:29:49 [error] 29#29: *2 no live upstreams while connecting to upstream, client: 172.18.0.1, server: panda.loc, request: "GET /openserver/phpmyadmin/ HTTP/1.1", upstream: "http://localhost/openserver/phpmyadmin/", host: "localhost"
2021/03/12 14:35:11 [error] 28#28: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET /openserver/phpmyadmin HTTP/1.1", upstream: "http://127.0.0.1:3001/openserver/phpmyadmin", host: "localhost"
2021/03/12 14:35:11 [warn] 28#28: *2 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET /openserver/phpmyadmin HTTP/1.1", upstream: "http://127.0.0.1:3001/openserver/phpmyadmin", host: "localhost"
2021/03/12 14:35:11 [error] 28#28: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET /openserver/phpmyadmin HTTP/1.1", upstream: "http://127.0.0.1:3001/openserver/phpmyadmin", host: "localhost"
2021/03/12 14:35:11 [warn] 28#28: *2 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET /openserver/phpmyadmin HTTP/1.1", upstream: "http://127.0.0.1:3001/openserver/phpmyadmin", host: "localhost"
2021/03/12 14:35:22 [error] 28#28: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:3001/favicon.ico", host: "localhost"
2021/03/12 14:35:22 [warn] 28#28: *5 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:3001/favicon.ico", host: "localhost"
2021/03/12 14:35:22 [error] 28#28: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:3001/favicon.ico", host: "localhost"
2021/03/12 14:35:22 [warn] 28#28: *5 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:3001/favicon.ico", host: "localhost"
2021/03/12 14:35:24 [error] 28#28: *2 no live upstreams while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "localhost"
2021/03/12 14:35:24 [error] 28#28: *2 no live upstreams while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost", referrer: "http://localhost/"
2021/03/12 14:36:06 [error] 28#28: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET //api/healthCheck HTTP/1.1", upstream: "http://127.0.0.1:3001//api/healthCheck", host: "localhost"
2021/03/12 14:36:06 [warn] 28#28: *2 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET //api/healthCheck HTTP/1.1", upstream: "http://127.0.0.1:3001//api/healthCheck", host: "localhost"
2021/03/12 14:36:06 [error] 28#28: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET //api/healthCheck HTTP/1.1", upstream: "http://127.0.0.1:3001//api/healthCheck", host: "localhost"
2021/03/12 14:36:06 [warn] 28#28: *2 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET //api/healthCheck HTTP/1.1", upstream: "http://127.0.0.1:3001//api/healthCheck", host: "localhost"
2021/03/12 14:36:06 [error] 28#28: *2 no live upstreams while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost", referrer: "http://localhost//api/healthCheck"
2021/03/12 14:36:11 [error] 28#28: *2 no live upstreams while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET /api/healthCheck HTTP/1.1", upstream: "http://localhost/api/healthCheck", host: "localhost"
2021/03/12 14:36:11 [error] 28#28: *2 no live upstreams while connecting to upstream, client: 172.19.0.1, server: panda.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost", referrer: "http://localhost/api/healthCheck"
2021/03/12 14:51:30 [emerg] 1#1: "http" directive is not allowed here in /etc/nginx/conf.d/default.conf:1
2021/03/12 16:09:02 [emerg] 1#1: invalid number of arguments in "root" directive in /etc/nginx/conf.d/default.conf:5
2021/03/12 16:09:08 [emerg] 1#1: invalid number of arguments in "root" directive in /etc/nginx/conf.d/default.conf:5
2021/03/12 16:09:13 [emerg] 1#1: invalid number of arguments in "root" directive in /etc/nginx/conf.d/default.conf:5
2021/03/12 16:09:43 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:09:43 [warn] 29#29: *1 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:09:43 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:09:43 [warn] 29#29: *1 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:09:43 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost:8080", referrer: "http://localhost:8080/"
2021/03/12 16:10:00 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:10:00 [warn] 29#29: *1 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:10:00 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:10:00 [warn] 29#29: *1 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:10:00 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost:8080", referrer: "http://localhost:8080/"
2021/03/12 16:10:07 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /app HTTP/1.1", upstream: "http://localhost/app", host: "localhost:8080"
2021/03/12 16:10:07 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost:8080", referrer: "http://localhost:8080/app"
2021/03/12 16:10:10 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /app/ HTTP/1.1", upstream: "http://localhost/app/", host: "localhost:8080"
2021/03/12 16:10:10 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost:8080", referrer: "http://localhost:8080/app/"
2021/03/12 16:10:21 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /api/healthcheck HTTP/1.1", upstream: "http://127.0.0.1:3001/api/healthcheck", host: "localhost:8080"
2021/03/12 16:10:21 [warn] 29#29: *1 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /api/healthcheck HTTP/1.1", upstream: "http://127.0.0.1:3001/api/healthcheck", host: "localhost:8080"
2021/03/12 16:10:21 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /api/healthcheck HTTP/1.1", upstream: "http://127.0.0.1:3001/api/healthcheck", host: "localhost:8080"
2021/03/12 16:10:21 [warn] 29#29: *1 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /api/healthcheck HTTP/1.1", upstream: "http://127.0.0.1:3001/api/healthcheck", host: "localhost:8080"
2021/03/12 16:10:21 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost:8080", referrer: "http://localhost:8080/api/healthcheck"
2021/03/12 16:12:31 [emerg] 1#1: directive "root" is not terminated by ";" in /etc/nginx/conf.d/default.conf:6
2021/03/12 16:13:15 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /api/healthcheck HTTP/1.1", upstream: "http://127.0.0.1:3001/api/healthcheck", host: "localhost:8080"
2021/03/12 16:13:15 [warn] 29#29: *2 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /api/healthcheck HTTP/1.1", upstream: "http://127.0.0.1:3001/api/healthcheck", host: "localhost:8080"
2021/03/12 16:13:15 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /api/healthcheck HTTP/1.1", upstream: "http://127.0.0.1:3001/api/healthcheck", host: "localhost:8080"
2021/03/12 16:13:15 [warn] 29#29: *2 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /api/healthcheck HTTP/1.1", upstream: "http://127.0.0.1:3001/api/healthcheck", host: "localhost:8080"
2021/03/12 16:13:15 [error] 29#29: *2 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost:8080", referrer: "http://localhost:8080/api/healthcheck"
2021/03/12 16:13:16 [error] 29#29: *2 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /api/healthcheck HTTP/1.1", upstream: "http://localhost/api/healthcheck", host: "localhost:8080"
2021/03/12 16:13:16 [error] 29#29: *2 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost:8080", referrer: "http://localhost:8080/api/healthcheck"
2021/03/12 16:13:57 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:13:57 [warn] 29#29: *2 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:13:57 [error] 29#29: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:13:57 [warn] 29#29: *2 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:13:57 [error] 29#29: *2 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "localhost:8080", referrer: "http://localhost:8080/"
2021/03/12 16:16:05 [error] 29#29: *1 "/APP/index.html" is not found (2: No such file or directory), client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", host: "localhost:8080"
2021/03/12 16:16:05 [error] 29#29: *1 open() "/APP/favicon.ico" failed (2: No such file or directory), client: 172.19.0.1, server: pandich.loc, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
2021/03/12 16:16:08 [error] 29#29: *1 open() "/APP/api" failed (2: No such file or directory), client: 172.19.0.1, server: pandich.loc, request: "GET /api HTTP/1.1", host: "localhost:8080"
2021/03/12 16:17:44 [error] 29#29: *3 "/APP/index.html" is not found (2: No such file or directory), client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", host: "localhost:8080"
2021/03/12 16:19:09 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:19:09 [warn] 29#29: *1 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:19:09 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:19:09 [warn] 29#29: *1 upstream server temporarily disabled while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "localhost:8080"
2021/03/12 16:19:10 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "localhost:8080"
2021/03/12 16:19:10 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "localhost:8080"
2021/03/12 16:19:10 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "localhost:8080"
2021/03/12 16:19:14 [error] 29#29: *1 no live upstreams while connecting to upstream, client: 172.19.0.1, server: pandich.loc, request: "GET /api HTTP/1.1", upstream: "http://localhost/api", host: "localhost:8080"
